package it.giovannidefilippo.gestionale.user;

public enum UserPermission {
    VIEW_CATALOG,
    VIEW_PARTNERS,
    MANAGE_PARTNERS,
    MANAGE_PRODUCTS,
    MANAGE_INVENTORY,
    VIEW_ORDERS,
    CREATE_ORDERS,
    CONFIRM_ORDERS,
    FULFILL_ORDERS,
    CANCEL_ORDERS,
    RECORD_PAYMENTS,
    REFUND_PAYMENTS,
    REQUEST_RETURNS,
    MANAGE_RETURNS,
    MANAGE_DOCUMENTS,
    VIEW_REPORTS,
    MANAGE_COMPANY_SETTINGS,
    MANAGE_ACCOUNTS,
    VIEW_AUDIT
}
