create table idempotency_records (
    id bigint generated by default as identity primary key,
    idem_key varchar(120) not null,
    actor varchar(255) not null,
    operation varchar(255) not null,
    request_hash varchar(64) not null,
    status varchar(32) not null,
    response_body text,
    response_type varchar(500),
    http_status integer,
    created_at timestamp(6) not null,
    completed_at timestamp(6),
    constraint uk_idempotency_actor_operation_key unique (actor, operation, idem_key)
);

create index idx_idempotency_created_at on idempotency_records (created_at);
