create table order_payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    method varchar(40) not null,
    method_details varchar(255),
    status varchar(40) not null,
    requested_amount numeric(12, 2) not null,
    paid_amount numeric(12, 2) not null,
    currency varchar(3) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    version bigint not null default 0,
    constraint uk_order_payments_order unique (order_id),
    constraint fk_order_payments_order foreign key (order_id) references customer_orders (id),
    constraint chk_order_payments_method check (method in ('CARD', 'BANK_TRANSFER', 'CASH', 'OTHER')),
    constraint chk_order_payments_status check (status in ('PENDING', 'PARTIALLY_PAID', 'PAID', 'FAILED', 'CANCELED', 'PARTIALLY_REFUNDED', 'REFUNDED')),
    constraint chk_order_payments_requested_not_negative check (requested_amount >= 0),
    constraint chk_order_payments_paid_not_negative check (paid_amount >= 0),
    constraint chk_order_payments_paid_not_over_requested check (paid_amount <= requested_amount),
    constraint chk_order_payments_currency check (char_length(trim(currency)) = 3)
);

insert into order_payments (order_id, method, method_details, status, requested_amount, paid_amount, currency, created_at, updated_at, version)
select
    id,
    case upper(trim(payment_method))
        when 'CARTA' then 'CARD'
        when 'CARD' then 'CARD'
        when 'BONIFICO' then 'BANK_TRANSFER'
        when 'BONIFICO BANCARIO' then 'BANK_TRANSFER'
        when 'BANK_TRANSFER' then 'BANK_TRANSFER'
        when 'CONTANTI' then 'CASH'
        when 'CASH' then 'CASH'
        else 'OTHER'
    end,
    case
        when upper(trim(payment_method)) in ('CARTA', 'CARD', 'BONIFICO', 'BONIFICO BANCARIO', 'BANK_TRANSFER', 'CONTANTI', 'CASH') then null
        else payment_method
    end,
    case when status = 'CANCELED' then 'CANCELED' else 'PENDING' end,
    total,
    0,
    'EUR',
    timestamp,
    status_changed_at,
    0
from customer_orders;

create index idx_order_payments_status on order_payments (status);
create index idx_order_payments_method on order_payments (method);
