alter table order_payments
    add column refunded_amount numeric(12, 2) not null default 0;

alter table order_payments
    add constraint chk_order_payments_refunded_not_negative check (refunded_amount >= 0);

alter table order_payments
    add constraint chk_order_payments_refunded_not_over_paid check (refunded_amount <= paid_amount);

create sequence payment_transaction_code_seq start with 1 increment by 1;
create sequence order_return_code_seq start with 1 increment by 1;

create table payment_transactions (
    id bigint generated by default as identity primary key,
    code varchar(40) not null,
    payment_id bigint not null,
    type varchar(20) not null,
    amount numeric(12, 2) not null,
    reference varchar(120),
    reason varchar(500) not null,
    return_code varchar(40),
    recorded_at timestamp(6) not null,
    recorded_by varchar(120) not null,
    recorded_by_role varchar(80) not null,
    constraint uk_payment_transactions_code unique (code),
    constraint fk_payment_transactions_payment foreign key (payment_id) references order_payments (id),
    constraint chk_payment_transactions_type check (type in ('RECEIPT', 'REFUND')),
    constraint chk_payment_transactions_amount_positive check (amount > 0),
    constraint chk_payment_transactions_reason_not_blank check (char_length(trim(reason)) > 0),
    constraint chk_payment_transactions_actor_not_blank check (char_length(trim(recorded_by)) > 0)
);

create table order_returns (
    id bigint generated by default as identity primary key,
    code varchar(40) not null,
    order_id bigint not null,
    status varchar(30) not null,
    reason varchar(500) not null,
    total_amount numeric(12, 2) not null,
    refunded_amount numeric(12, 2) not null default 0,
    requested_at timestamp(6) not null,
    requested_by varchar(120) not null,
    requested_by_role varchar(80) not null,
    reviewed_at timestamp(6),
    reviewed_by varchar(120),
    review_note varchar(500),
    received_at timestamp(6),
    received_by varchar(120),
    updated_at timestamp(6) not null,
    version bigint not null default 0,
    constraint uk_order_returns_code unique (code),
    constraint fk_order_returns_order foreign key (order_id) references customer_orders (id),
    constraint chk_order_returns_status check (status in ('REQUESTED', 'APPROVED', 'REJECTED', 'RECEIVED', 'PARTIALLY_REFUNDED', 'REFUNDED')),
    constraint chk_order_returns_reason_not_blank check (char_length(trim(reason)) > 0),
    constraint chk_order_returns_total_positive check (total_amount > 0),
    constraint chk_order_returns_refunded_not_negative check (refunded_amount >= 0),
    constraint chk_order_returns_refunded_not_over_total check (refunded_amount <= total_amount),
    constraint chk_order_returns_requester_not_blank check (char_length(trim(requested_by)) > 0)
);

create table order_return_items (
    id bigint generated by default as identity primary key,
    return_id bigint not null,
    product_code varchar(120) not null,
    product_name varchar(255) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    line_total numeric(12, 2) not null,
    constraint uk_order_return_items_product unique (return_id, product_code),
    constraint fk_order_return_items_return foreign key (return_id) references order_returns (id),
    constraint chk_order_return_items_code_not_blank check (char_length(trim(product_code)) > 0),
    constraint chk_order_return_items_quantity_positive check (quantity > 0),
    constraint chk_order_return_items_unit_price_not_negative check (unit_price >= 0),
    constraint chk_order_return_items_line_total_not_negative check (line_total >= 0)
);

create index idx_payment_transactions_payment on payment_transactions (payment_id, recorded_at);
create index idx_payment_transactions_return on payment_transactions (return_code);
create index idx_order_returns_order on order_returns (order_id, requested_at);
create index idx_order_returns_status on order_returns (status);
