create table products (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    name varchar(255) not null,
    description varchar(1200) not null,
    category varchar(255) not null,
    brand varchar(255) not null,
    product_type varchar(255) not null,
    usage_context varchar(255),
    quantity integer not null,
    price numeric(12, 2) not null,
    discount numeric(5, 2) not null,
    constraint uk_products_code unique (code)
);

create table user_accounts (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password_salt varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null,
    constraint uk_user_accounts_username unique (username)
);

create table customer_orders (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    customer varchar(255) not null,
    timestamp timestamp(6) not null,
    payment_method varchar(255) not null,
    total numeric(12, 2) not null,
    constraint uk_customer_orders_code unique (code)
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_code varchar(255) not null,
    product_name varchar(255) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    line_total numeric(12, 2) not null,
    constraint fk_order_items_order foreign key (order_id) references customer_orders (id)
);

create table stock_movements (
    id bigint generated by default as identity primary key,
    timestamp timestamp(6) not null,
    actor varchar(255) not null,
    role varchar(255) not null,
    product_code varchar(255) not null,
    product_name varchar(255) not null,
    type varchar(255) not null,
    quantity integer not null,
    previous_quantity integer not null,
    new_quantity integer not null,
    reason varchar(900) not null
);

create table fiscal_documents (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    type varchar(255) not null,
    status varchar(255) not null,
    created_at timestamp(6) not null,
    related_order_code varchar(255) not null,
    customer varchar(255) not null,
    payment_method varchar(255) not null,
    taxable_amount numeric(12, 2) not null,
    vat_rate numeric(5, 2) not null,
    vat_amount numeric(12, 2) not null,
    total_amount numeric(12, 2) not null,
    created_by varchar(255) not null,
    created_by_role varchar(255) not null,
    reason varchar(900) not null,
    disclaimer varchar(255) not null,
    constraint uk_fiscal_documents_code unique (code)
);

create table fiscal_document_lines (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    product_code varchar(255) not null,
    description varchar(255) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    line_total numeric(12, 2) not null,
    constraint fk_fiscal_document_lines_document foreign key (document_id) references fiscal_documents (id)
);

create table audit_events (
    id bigint generated by default as identity primary key,
    timestamp timestamp(6) not null,
    actor varchar(255) not null,
    role varchar(255) not null,
    action varchar(255) not null,
    target varchar(255) not null,
    details varchar(1200) not null,
    category varchar(255) not null,
    severity varchar(255) not null
);

create index idx_order_items_order_id on order_items (order_id);
create index idx_customer_orders_customer on customer_orders (customer);
create index idx_stock_movements_product_code on stock_movements (product_code);
create index idx_stock_movements_timestamp on stock_movements (timestamp);
create index idx_fiscal_document_lines_document_id on fiscal_document_lines (document_id);
create index idx_fiscal_documents_related_order_code on fiscal_documents (related_order_code);
create index idx_audit_events_timestamp on audit_events (timestamp);
create index idx_audit_events_category on audit_events (category);
