create table auth_sessions (
    id bigint generated by default as identity primary key,
    token_hash varchar(128) not null,
    username varchar(255) not null,
    role varchar(255) not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    revoked_at timestamp(6),
    constraint uk_auth_sessions_token_hash unique (token_hash)
);

create index idx_auth_sessions_username on auth_sessions (username);
create index idx_auth_sessions_expires_at on auth_sessions (expires_at);
create index idx_auth_sessions_revoked_at on auth_sessions (revoked_at);
