create sequence supplier_order_code_seq start with 1 increment by 1;
create sequence supplier_receipt_code_seq start with 1 increment by 1;

create table supplier_orders (
    id bigint generated by default as identity primary key,
    version bigint not null default 0,
    code varchar(255) not null,
    supplier_id bigint not null,
    supplier_code_snapshot varchar(255) not null,
    supplier_name_snapshot varchar(255) not null,
    status varchar(32) not null,
    expected_delivery_date date not null,
    notes varchar(1200) not null default '',
    total numeric(14, 2) not null,
    currency varchar(3) not null default 'EUR',
    created_at timestamp(6) not null,
    created_by varchar(255) not null,
    created_by_role varchar(255) not null,
    sent_at timestamp(6),
    canceled_at timestamp(6),
    canceled_by varchar(255),
    canceled_by_role varchar(255),
    cancellation_reason varchar(900),
    constraint uk_supplier_orders_code unique (code),
    constraint fk_supplier_orders_supplier foreign key (supplier_id) references business_partners (id),
    constraint chk_supplier_orders_status check (status in ('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELED')),
    constraint chk_supplier_orders_total check (total >= 0),
    constraint chk_supplier_orders_currency check (currency = 'EUR'),
    constraint chk_supplier_orders_snapshots check (char_length(trim(supplier_code_snapshot)) > 0 and char_length(trim(supplier_name_snapshot)) > 0),
    constraint chk_supplier_orders_cancellation check (
        (status <> 'CANCELED' and canceled_at is null and canceled_by is null and canceled_by_role is null and cancellation_reason is null)
        or
        (status = 'CANCELED' and canceled_at is not null and char_length(trim(canceled_by)) > 0 and char_length(trim(canceled_by_role)) > 0 and char_length(trim(cancellation_reason)) > 0)
    ),
    constraint chk_supplier_orders_sent check (
        status in ('DRAFT', 'CANCELED') or sent_at is not null
    )
);

create table supplier_order_items (
    id bigint generated by default as identity primary key,
    supplier_order_id bigint not null,
    product_id bigint not null,
    product_code_snapshot varchar(255) not null,
    product_name_snapshot varchar(255) not null,
    ordered_quantity integer not null,
    received_quantity integer not null default 0,
    unit_price numeric(12, 2) not null,
    line_total numeric(14, 2) not null,
    expected_delivery_date date not null,
    constraint fk_supplier_order_items_order foreign key (supplier_order_id) references supplier_orders (id) on delete cascade,
    constraint fk_supplier_order_items_product foreign key (product_id) references products (id),
    constraint uk_supplier_order_items_product unique (supplier_order_id, product_id),
    constraint chk_supplier_order_items_snapshots check (char_length(trim(product_code_snapshot)) > 0 and char_length(trim(product_name_snapshot)) > 0),
    constraint chk_supplier_order_items_quantities check (ordered_quantity > 0 and received_quantity >= 0 and received_quantity <= ordered_quantity),
    constraint chk_supplier_order_items_amounts check (unit_price >= 0 and line_total = unit_price * ordered_quantity)
);

create table supplier_order_receipts (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    supplier_order_id bigint not null,
    reason varchar(900) not null,
    received_at timestamp(6) not null,
    received_by varchar(255) not null,
    received_by_role varchar(255) not null,
    constraint uk_supplier_order_receipts_code unique (code),
    constraint fk_supplier_order_receipts_order foreign key (supplier_order_id) references supplier_orders (id),
    constraint chk_supplier_order_receipts_reason check (char_length(trim(reason)) > 0)
);

create table supplier_order_receipt_items (
    id bigint generated by default as identity primary key,
    receipt_id bigint not null,
    supplier_order_item_id bigint not null,
    quantity integer not null,
    constraint fk_supplier_order_receipt_items_receipt foreign key (receipt_id) references supplier_order_receipts (id) on delete cascade,
    constraint fk_supplier_order_receipt_items_line foreign key (supplier_order_item_id) references supplier_order_items (id),
    constraint uk_supplier_order_receipt_items_line unique (receipt_id, supplier_order_item_id),
    constraint chk_supplier_order_receipt_items_quantity check (quantity > 0)
);

create index idx_supplier_orders_status_created on supplier_orders (status, created_at);
create index idx_supplier_orders_supplier on supplier_orders (supplier_id, created_at);
create index idx_supplier_orders_expected_date on supplier_orders (expected_delivery_date);
create index idx_supplier_order_items_order on supplier_order_items (supplier_order_id);
create index idx_supplier_order_items_product on supplier_order_items (product_id);
create index idx_supplier_order_receipts_order on supplier_order_receipts (supplier_order_id, received_at);
create index idx_supplier_order_receipt_items_receipt on supplier_order_receipt_items (receipt_id);
