create sequence physical_inventory_session_code_seq start with 1 increment by 1;

create table physical_inventory_sessions (
    id bigint generated by default as identity primary key,
    version bigint not null default 0,
    code varchar(255) not null,
    status varchar(32) not null,
    reason varchar(900) not null,
    created_at timestamp(6) not null,
    created_by varchar(255) not null,
    created_by_role varchar(255) not null,
    submitted_at timestamp(6),
    submitted_by varchar(255),
    submitted_by_role varchar(255),
    approved_at timestamp(6),
    approved_by varchar(255),
    approved_by_role varchar(255),
    approval_reason varchar(900),
    canceled_at timestamp(6),
    canceled_by varchar(255),
    canceled_by_role varchar(255),
    cancellation_reason varchar(900),
    constraint uk_physical_inventory_sessions_code unique (code),
    constraint chk_physical_inventory_sessions_status check (status in ('OPEN', 'SUBMITTED', 'APPROVED', 'CANCELED')),
    constraint chk_physical_inventory_sessions_reason check (char_length(trim(reason)) > 0),
    constraint chk_physical_inventory_sessions_lifecycle check (
        (status = 'OPEN' and submitted_at is null and submitted_by is null and submitted_by_role is null and approved_at is null and approved_by is null and approved_by_role is null and approval_reason is null and canceled_at is null and canceled_by is null and canceled_by_role is null and cancellation_reason is null)
        or
        (status = 'SUBMITTED' and submitted_at is not null and char_length(trim(submitted_by)) > 0 and char_length(trim(submitted_by_role)) > 0 and approved_at is null and approved_by is null and approved_by_role is null and approval_reason is null and canceled_at is null and canceled_by is null and canceled_by_role is null and cancellation_reason is null)
        or
        (status = 'APPROVED' and submitted_at is not null and char_length(trim(submitted_by)) > 0 and char_length(trim(submitted_by_role)) > 0 and approved_at is not null and char_length(trim(approved_by)) > 0 and char_length(trim(approved_by_role)) > 0 and char_length(trim(approval_reason)) > 0 and canceled_at is null and canceled_by is null and canceled_by_role is null and cancellation_reason is null)
        or
        (status = 'CANCELED' and approved_at is null and approved_by is null and approved_by_role is null and approval_reason is null and canceled_at is not null and char_length(trim(canceled_by)) > 0 and char_length(trim(canceled_by_role)) > 0 and char_length(trim(cancellation_reason)) > 0)
    ),
    constraint chk_physical_inventory_separation check (approved_by is null or lower(approved_by) <> lower(submitted_by))
);

create table physical_inventory_items (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    product_id bigint not null,
    product_code_snapshot varchar(255) not null,
    product_name_snapshot varchar(255) not null,
    theoretical_quantity_snapshot integer not null,
    reserved_quantity_snapshot integer not null,
    product_version_snapshot bigint not null,
    counted_quantity integer,
    theoretical_quantity_at_count integer,
    reserved_quantity_at_count integer,
    product_version_at_count bigint,
    difference_quantity integer,
    counted_at timestamp(6),
    counted_by varchar(255),
    counted_by_role varchar(255),
    count_note varchar(900),
    quantity_before_approval integer,
    quantity_after_approval integer,
    reserved_quantity_at_approval integer,
    compensated_movement_delta integer,
    stock_movement_id bigint,
    active_marker boolean default true,
    constraint fk_physical_inventory_items_session foreign key (session_id) references physical_inventory_sessions (id),
    constraint fk_physical_inventory_items_product foreign key (product_id) references products (id),
    constraint uk_physical_inventory_items_session_product unique (session_id, product_id),
    constraint uk_physical_inventory_items_active_product unique (product_id, active_marker),
    constraint chk_physical_inventory_items_snapshot check (
        char_length(trim(product_code_snapshot)) > 0
        and char_length(trim(product_name_snapshot)) > 0
        and theoretical_quantity_snapshot >= 0
        and reserved_quantity_snapshot >= 0
        and reserved_quantity_snapshot <= theoretical_quantity_snapshot
        and product_version_snapshot >= 0
    ),
    constraint chk_physical_inventory_items_count check (
        (counted_quantity is null and theoretical_quantity_at_count is null and reserved_quantity_at_count is null and product_version_at_count is null and difference_quantity is null and counted_at is null and counted_by is null and counted_by_role is null and count_note is null)
        or
        (counted_quantity >= 0 and theoretical_quantity_at_count >= 0 and reserved_quantity_at_count >= 0 and reserved_quantity_at_count <= theoretical_quantity_at_count and product_version_at_count >= 0 and difference_quantity = counted_quantity - theoretical_quantity_at_count and counted_at is not null and char_length(trim(counted_by)) > 0 and char_length(trim(counted_by_role)) > 0)
    ),
    constraint chk_physical_inventory_items_approval check (
        (quantity_before_approval is null and quantity_after_approval is null and reserved_quantity_at_approval is null and compensated_movement_delta is null and stock_movement_id is null)
        or
        (quantity_before_approval >= 0 and quantity_after_approval >= 0 and reserved_quantity_at_approval >= 0 and reserved_quantity_at_approval <= quantity_after_approval and compensated_movement_delta = quantity_before_approval - theoretical_quantity_at_count and quantity_after_approval = quantity_before_approval + difference_quantity and ((difference_quantity = 0 and stock_movement_id is null) or (difference_quantity <> 0 and stock_movement_id is not null)))
    ),
    constraint chk_physical_inventory_items_active_marker check (active_marker is null or active_marker = true)
);

alter table stock_movements add column physical_inventory_session_id bigint;
alter table stock_movements add column physical_inventory_item_id bigint;

alter table stock_movements drop constraint chk_stock_movements_origin;
alter table stock_movements
    add constraint chk_stock_movements_origin
        check (origin in ('LEGACY', 'MIGRATION_BASELINE', 'MANUAL_INITIAL_BALANCE', 'MANUAL_ADJUSTMENT', 'MANUAL_MOVEMENT', 'ORDER_FULFILLMENT', 'CUSTOMER_RETURN', 'SUPPLIER_ORDER_RECEIPT', 'PHYSICAL_INVENTORY'));

alter table stock_movements
    add constraint fk_stock_movements_physical_inventory_session
        foreign key (physical_inventory_session_id) references physical_inventory_sessions (id);
alter table stock_movements
    add constraint fk_stock_movements_physical_inventory_item
        foreign key (physical_inventory_item_id) references physical_inventory_items (id);
alter table stock_movements
    add constraint uk_stock_movements_physical_inventory_item unique (physical_inventory_item_id);
alter table stock_movements
    add constraint chk_stock_movements_physical_inventory check (
        (origin = 'PHYSICAL_INVENTORY' and type in ('PHYSICAL_INVENTORY_INCREASE', 'PHYSICAL_INVENTORY_DECREASE') and physical_inventory_session_id is not null and physical_inventory_item_id is not null)
        or
        (origin <> 'PHYSICAL_INVENTORY' and physical_inventory_session_id is null and physical_inventory_item_id is null)
    );

alter table physical_inventory_items
    add constraint fk_physical_inventory_items_stock_movement foreign key (stock_movement_id) references stock_movements (id);
alter table physical_inventory_items
    add constraint uk_physical_inventory_items_stock_movement unique (stock_movement_id);

create index idx_physical_inventory_sessions_status_created on physical_inventory_sessions (status, created_at);
create index idx_physical_inventory_items_session on physical_inventory_items (session_id, product_code_snapshot);
create index idx_stock_movements_physical_inventory on stock_movements (physical_inventory_session_id, timestamp);
