create table login_attempts (
    id bigint generated by default as identity primary key,
    username_key varchar(255) not null,
    attempts integer not null,
    first_attempt_at timestamp(6) not null,
    last_attempt_at timestamp(6) not null,
    locked_until timestamp(6),
    constraint uk_login_attempts_username_key unique (username_key)
);

create index idx_login_attempts_locked_until on login_attempts (locked_until);
create index idx_login_attempts_last_attempt_at on login_attempts (last_attempt_at);
