create table business_partners (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    type varchar(255) not null,
    display_name varchar(255) not null,
    tax_code varchar(255),
    vat_number varchar(255),
    email varchar(255),
    phone varchar(255),
    address varchar(600),
    city varchar(255),
    notes varchar(1200),
    active boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint uk_business_partners_code unique (code)
);

alter table customer_orders add column customer_code varchar(255);

create index idx_business_partners_type on business_partners (type);
create index idx_business_partners_display_name on business_partners (display_name);
create index idx_customer_orders_customer_code on customer_orders (customer_code);
