package it.giovannidefilippo.gestionale.order;

public enum FinancialMismatchType {
    PAYMENT_PAID_LEDGER_DRIFT,
    PAYMENT_REFUNDED_LEDGER_DRIFT,
    PAYMENT_INVALID_STATE,
    PAYMENT_INVALID_TIMELINE,
    PAYMENT_INVALID_TRANSACTION_LINK,
    PAYMENT_UNRECONCILED,
    RETURN_REFUNDED_LEDGER_DRIFT,
    RETURN_INVALID_STATE,
    RETURN_INVALID_TIMELINE
}
